.TH .GET_CONTEXT 1 2025-Oct "" "get current workflow environment context"
.SH NAME
.get_context \- .get_context(
    <i>ssid</i> = <span style='color: blue !important;'>NULL</span>)
.SH SYNOPSIS
\fI.get_context(
    <i>ssid</i> = <span style='color: blue !important;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBssid\fB \fR\- NULL. the session id for multiple user environment, default NULL means global user environment
.PP
.SH VALUE
.PP
the context object which is generated via the
``init_context`` function.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function..get_context at context.R:line 78
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
