.TH .INTERNAL_CALL 1 2024-May "" "Invoke an analysis application"
.SH NAME
.internal_call \- .internal_call(app, context)
.SH SYNOPSIS
\fI.internal_call(app, context)\fR
.SH OPTIONS
.PP
\fBapp\fB \fR\- . 
.PP
.PP
\fBcontext\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function..internal_call at runner.R:line 3
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2024
