.TH __BUILD_APP 1 2025-Jun "" "Build workflow app object"
.SH NAME
__build_app \- __build_app(f)
.SH SYNOPSIS
\fI__build_app(f)\fR
.SH OPTIONS
.PP
\fBf\fB \fR\- . the target function f which tagged the required attribute data inside: app, desc, context_env, workfiles
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.__build_app at reflection.R:line 11
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
