.TH __RUNIMPL 1 2023-May "" "An internal function for start the workflow"
.SH NAME
__runImpl \- __runImpl(context)
.SH SYNOPSIS
\fI__runImpl(context)\fR
.SH OPTIONS
.PP
\fBcontext\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.__runImpl at workflowRender.R:line 18
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
