.TH __WORKFILE_URI_PARSER 1 2025-Feb "" "parse the workfile expression"
.SH NAME
__workfile_uri_parser \- __workfile_uri_parser(uri)
.SH SYNOPSIS
\fI__workfile_uri_parser(uri)\fR
.SH OPTIONS
.PP
\fBuri\fB \fR\- . a character vector that contains the workfile reference expression.
.PP
.SH VALUE
.PP
a tuple list object that contains the necessary parameter value for call ``workfile`` function for gets the reference file path to the required data files.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.__workfile_uri_parser at reflection.R:line 61
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
