.TH __WORKFILE_URI_PARSER 1 2024-Jan "" "__workfile_uri_parser"
.SH NAME
__workfile_uri_parser \- __workfile_uri_parser(uri)
.SH SYNOPSIS
\fI__workfile_uri_parser(uri)\fR
.SH OPTIONS
.PP
\fBuri\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.__workfile_uri_parser at reflection.R:line 44
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2024
