.TH __WORKFILES_DATA 1 2026-2月 "" "__workfiles_data"
.SH NAME
__workfiles_data \- __workfiles_data(files.uri)
.SH SYNOPSIS
\fI__workfiles_data(files.uri)\fR
.SH OPTIONS
.PP
\fBfiles.uri\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.__workfiles_data at reflection.R:line 58
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2026
