.TH __WORKFILES 1 2026-Jan "" "__workfiles"
.SH NAME
__workfiles \- __workfiles(files.uri)
.SH SYNOPSIS
\fI__workfiles(files.uri)\fR
.SH OPTIONS
.PP
\fBfiles.uri\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.__workfiles at reflection.R:line 50
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2026
