.TH APP 1 2026-2月 "" "Analysis app constructor"
.SH NAME
app \- app(name, analysis,
    <i>desc</i> = <span style='color: brown;'><strong>'no description'</strong></span>,
    <i>dependency</i> = <span style='color: blue !important;'>NULL</span>)
.SH SYNOPSIS
\fIapp(name, analysis,
    <i>desc</i> = <span style='color: brown;'><strong>'no description'</strong></span>,
    <i>dependency</i> = <span style='color: blue !important;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBname\fB \fR\- . the analysis app name
.PP
.PP
\fBanalysis\fB \fR\- . a callable function for run the data analysis
content. The function declare signature for this parameter
value required of two parameter signature, see comment document
of the ``app_check.delegate`` function.
.PP
.PP
\fBdesc\fB \fR\- 'no description'. 
.PP
.PP
\fBdependency\fB \fR\- NULL. usually be the environment context symbol
dependency or the workspace file dependency
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.app at app.R:line 13
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2026
