.TH APP 1 2025-Aug "" "Analysis app constructor"
.SH NAME
app \- app(name, analysis,
    <i>desc</i> = <span style='color: brown;'><strong>'no description'</strong></span>,
    <i>dependency</i> = <span style='color: blue !important;'>NULL</span>)
.SH SYNOPSIS
\fIapp(name, analysis,
    <i>desc</i> = <span style='color: brown;'><strong>'no description'</strong></span>,
    <i>dependency</i> = <span style='color: blue !important;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBname\fB \fR\- . the analysis app name
.PP
.PP
\fBanalysis\fB \fR\- . 
.PP
.PP
\fBdesc\fB \fR\- 'no description'. 
.PP
.PP
\fBdependency\fB \fR\- NULL. usually be the environment context symbol dependency or the workspace file dependency
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.app at app.R:line 13
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
