.TH APP_CHECK.SIGNATURE 1 2023-Oct "" "check of the required app slot"
.SH NAME
app_check.signature \- app_check.signature(app)
.SH SYNOPSIS
\fIapp_check.signature(app)\fR
.SH OPTIONS
.PP
\fBapp\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.app_check.signature at app.R:line 33
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
