.TH APP_CHECK.DELEGATE 1 2026-7月 "internal" "Check the Application Module Object Signature"
.SH NAME
app_check.delegate \- app_check.delegate(analysis)
.SH SYNOPSIS
\fIapp_check.delegate(analysis)\fR
.SH DESCRIPTION
.PP


Validates that the supplied application object has the correct
structure to be registered into the workflow context. The function
checks that the object is a list with the expected slots and that
the \code{call} slot is a callable function.
.PP
.SH OPTIONS
.PP
\fBanalysis\fB \fR\- . 
.PP
.SH VALUE
.PP
A logical value that indicates whether the supplied application
object has the correct signature. The value \code{TRUE} is
returned when the object passes all of the following checks:
\itemize{
\item it is a list object;
\item it contains the slots \code{name}, \code{call},
\code{desc}, \code{dependency} and \code{disable};
\item the \code{call} slot is a callable function.
}
The value \code{FALSE} is returned otherwise.
.PP
.SH DETAILS
.PP
This function is invoked by \code{\link{hook}} to ensure that the
supplied application object was constructed via the
\code{\link{app}} function (or via \code{\link{__build_app}}) and
therefore has the expected structure. When the check fails, the
workflow is aborted via \code{\link{throw_err}} with an
appropriate error message.
.PP
.SH SEE ALSO
\code{\link{app_check.delegate}}, \code{\link{app}},
\code{\link{hook}}, \code{\link{throw_err}}
.SH FILES
.PP
SMRUCC/R#.declare_function.app_check.delegate at validation.R:line 68
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT + file LICENSE Licensed 2026
