.TH BUILDGRAPH 1 2023-Mar "" "Build graph from table content"
.SH NAME
buildGraph \- buildGraph(table)
.SH SYNOPSIS
\fIbuildGraph(table)\fR
.SH OPTIONS
.PP
\fBtable\fB \fR\- . the edges list data in dataframe format. edges table of this parameter, that must contains at least two fields: ``from`` and ``to``; some edge property likes ``weight``, ``type``, ``color``, ``width``, ``dash`` can be optional.
.PP
.SH VALUE
.PP
a network graph object
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.buildGraph at graph.R:line 11
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
