.TH BUILDGRAPH 1 2021-05-26 "" "Build graph from table content"
.SH NAME
buildGraph \- buildGraph(table, nodes = NULL)
.SH SYNOPSIS
\fIbuildGraph(table, nodes = NULL)\fR
.SH OPTIONS
.PP
\fBtable\fB \fR\- 
.PP
.PP
\fBnodes\fB \fR\- NULL
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.buildGraph at graph.R:line 11
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2021
