.TH CHECK_DEPENDENCY.CONTEXT_ENV 1 2023-May "" "check_dependency.context_env"
.SH NAME
check_dependency.context_env \- check_dependency.context_env(requires, context)
.SH SYNOPSIS
\fIcheck_dependency.context_env(requires, context)\fR
.SH OPTIONS
.PP
\fBrequires\fB \fR\- . 
.PP
.PP
\fBcontext\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.check_dependency.context_env at check_dependency.R:line 38
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
