.TH CHECK_DEPENDENCY.CONTEXT_ENV 1 2023-May "" "Check of the required environment symbols"
.SH NAME
check_dependency.context_env \- check_dependency.context_env(requires, context)
.SH SYNOPSIS
\fIcheck_dependency.context_env(requires, context)\fR
.SH OPTIONS
.PP
\fBrequires\fB \fR\- . 
.PP
.PP
\fBcontext\fB \fR\- . 
.PP
.SH DETAILS
.PP
the environment symbols from the analysis context should be set via the ``set_config`` function.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.check_dependency.context_env at check_dependency.R:line 46
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
