.TH CHECK_DEPENDENCY.LOCALFILES 1 2023-Jun "" "Check for the upstream file dependency"
.SH NAME
check_dependency.localfiles \- check_dependency.localfiles(requires, context)
.SH SYNOPSIS
\fIcheck_dependency.localfiles(requires, context)\fR
.SH OPTIONS
.PP
\fBrequires\fB \fR\- . 
.PP
.PP
\fBcontext\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.check_dependency.localfiles at check_dependency.R:line 80
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
