.TH CHECK_DEPENDENCY 1 2026-2月 "" "Check of the analysis app dependency"
.SH NAME
check_dependency \- check_dependency(app,
    <i>context</i> = '.get_context'())
.SH SYNOPSIS
\fIcheck_dependency(app,
    <i>context</i> = '.get_context'())\fR
.SH OPTIONS
.PP
\fBapp\fB \fR\- . the analysis app object list which is construct
via the ``app`` function.
.PP
.PP
\fBcontext\fB \fR\- '.get_context'(). 
.PP
.SH VALUE
.PP
this function returns a data list that contains the
dependency check result. there are some data symbol inside
this result object list:
1. check: logical, for indicate the dependency check success or not;
2. context: a tuple list object that contains of context symbol names
which are not check success, and the reason of failure;
3. file: character vector of dependency of local workspace file
check not success
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.check_dependency at check_dependency.R:line 16
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2026
