.TH DEFINEPIPELINE 1 2023-Oct "" "Create a custom pipeline workflow execute sequence"
.SH NAME
definePipeline \- definePipeline(seq)
.SH SYNOPSIS
\fIdefinePipeline(seq)\fR
.SH OPTIONS
.PP
\fBseq\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.definePipeline at definePipeline.R:line 3
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
