.TH DEFINEPIPELINE 1 2024-Apr "" "Create a custom pipeline workflow execute sequence"
.SH NAME
definePipeline \- definePipeline(seq)
.SH SYNOPSIS
\fIdefinePipeline(seq)\fR
.SH OPTIONS
.PP
\fBseq\fB \fR\- . a character vector of the app module names inside the workflow.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.definePipeline at definePipeline.R:line 5
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2024
