.TH DEPENDENCY_GRAPH 1 2024-May "" "try to extract the dependency graph from the application modules"
.SH NAME
dependency_graph \- dependency_graph()
.SH SYNOPSIS
\fIdependency_graph()\fR
.SH FILES
.PP
SMRUCC/R#.declare_function.dependency_graph at dependency_graph.R:line 3
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2024
