.TH DEPENDENCY_ANALYSIS 1 2025-Aug "" "dependency_analysis"
.SH NAME
dependency_analysis \- dependency_analysis(app)
.SH SYNOPSIS
\fIdependency_analysis(app)\fR
.SH OPTIONS
.PP
\fBapp\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.dependency_analysis at dependency_graph.R:line 119
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
