.TH ECHO_WARNING 1 2023-May "" "print warning message on the screen and the log file"
.SH NAME
echo_warning \- echo_warning(msg)
.SH SYNOPSIS
\fIecho_warning(msg)\fR
.SH OPTIONS
.PP
\fBmsg\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.echo_warning at utils.R:line 3
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
