.TH EXTRACT_WORKFLOW_VERTEX 1 2025-Oct "" "extract_workflow_vertex"
.SH NAME
extract_workflow_vertex \- extract_workflow_vertex(meta)
.SH SYNOPSIS
\fIextract_workflow_vertex(meta)\fR
.SH OPTIONS
.PP
\fBmeta\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.extract_workflow_vertex at dependency_graph.R:line 84
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
