.TH FILEPATH_SAFE 1 2025-May "" "Create the file path safely"
.SH NAME
filepath_safe \- filepath_safe(dir, filename,
    <i>maxchars</i> = <span style='color: green;'>48</span>)
.SH SYNOPSIS
\fIfilepath_safe(dir, filename,
    <i>maxchars</i> = <span style='color: green;'>48</span>)\fR
.SH OPTIONS
.PP
\fBdir\fB \fR\- . 
.PP
.PP
\fBfilename\fB \fR\- . 
.PP
.PP
\fBmaxchars\fB \fR\- 48. 
.PP
.SH VALUE
.PP
this function generates a new character vector based on the input dir and the filename for save a file safely.
.PP
.SH DETAILS
.PP
this function will make a safe file path, by processing the file name string in process: 1. removes the unsafe character for windows filesystem 2. make the file name short if the file name string len exccede the max chars
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.filepath_safe at filetools.R:line 12
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
