.TH FINALIZE 1 2024-Mar "" "Mark end of the analysis workflow"
.SH NAME
finalize \- finalize()
.SH SYNOPSIS
\fIfinalize()\fR
.SH DETAILS
.PP
release the resources of the pipeline workflow modules
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.finalize at finalize.R:line 5
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2024
