.TH GET_TIMESTAMP 1 2025-Jan "" "get a character vector of current timespan"
.SH NAME
get_timestamp \- get_timestamp()
.SH SYNOPSIS
\fIget_timestamp()\fR
.SH DETAILS
.PP
this character vector of the current timespan could be used inside a file path safely.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.get_timestamp at utils.R:line 42
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
