.TH GET_APPNAME.OBJ 1 2026-7月 "internal" "Get the Application Name from an Application Object"
.SH NAME
get_appName.obj \- get_appName.obj(app)
.SH SYNOPSIS
\fIget_appName.obj(app)\fR
.SH DESCRIPTION
.PP


Extracts the application name from an analysis application object
that has been constructed via the \code{\link{app}} function. This
is the simplest implementation of the \code{\link{get_app_name}}
generic function and is used as the fallback when the supplied
object is already a fully-formed application list.
.PP
.SH OPTIONS
.PP
\fBapp\fB \fR\- . the application object whose name should be extracted.
The object is expected to be a list with a \code{name} slot, as
produced by \code{\link{app}}.
.PP
.SH VALUE
.PP
A character vector of the application name extracted from the
\code{name} slot of the supplied object.
.PP
.SH DETAILS
.PP
This function is registered as the default method of the
\code{\link{get_app_name}} generic function. When the supplied
object is a list with a \code{name} slot, the function simply
returns the value of that slot. When the supplied object is a
bare function reference, the more specialized
\code{\link{get_app_name.func_reference}} method is invoked
instead.
.PP
.SH SEE ALSO
\code{\link{get_app_name}},
\code{\link{get_app_name.func_reference}}, \code{\link{app}}
.SH FILES
.PP
SMRUCC/R#.declare_function.get_appName.obj at appname_obj.R:line 32
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT + file LICENSE Licensed 2026
