.TH GET_APP_NAME 1 2025-May "" "Helper function for get app name"
.SH NAME
get_app_name \- get_app_name(app)
.SH SYNOPSIS
\fIget_app_name(app)\fR
.SH OPTIONS
.PP
\fBapp\fB \fR\- . the app object list itself or the character vector of the name value
.PP
.SH VALUE
.PP
this function always returns the app name character vector
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.get_app_name at app_name.R:line 10
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
