.TH GET_APPNAME.OBJ 1 2023-Aug "" "Get app name from the generated analysis app module"
.SH NAME
get_appName.obj \- get_appName.obj(app)
.SH SYNOPSIS
\fIget_appName.obj(app)\fR
.SH OPTIONS
.PP
\fBapp\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.get_appName.obj at app_name.R:line 36
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
