.TH GET_APPNAME.FUNC_REFERENCE 1 2026-Jan "" "get_appName.func_reference"
.SH NAME
get_appName.func_reference \- get_appName.func_reference(app)
.SH SYNOPSIS
\fIget_appName.func_reference(app)\fR
.SH OPTIONS
.PP
\fBapp\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.get_appName.func_reference at app_name.R:line 52
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2026
