.TH GET_CONFIG 1 2025-Jun "" "get user parameter value inside current workflow context environment"
.SH NAME
get_config \- get_config(name,
    <i>default</i> = <span style='color: blue !important;'>NULL</span>,
    <i>warn.msg</i> = <span style='color: blue !important;'>NULL</span>)
.SH SYNOPSIS
\fIget_config(name,
    <i>default</i> = <span style='color: blue !important;'>NULL</span>,
    <i>warn.msg</i> = <span style='color: blue !important;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBname\fB \fR\- . 
.PP
.PP
\fBdefault\fB \fR\- NULL. the default value for the parameter if missing from the workflow context environment.
.PP
.PP
\fBwarn.msg\fB \fR\- NULL. 
.PP
.SH VALUE
.PP
the parameter value, maybe is object value in character type, a type cast function expression invoke example as: ``as.logical``, ``as.double``, etc maybe required.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.get_config at set_config.R:line 41
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
