.TH GET_FUNCTIONNAME 1 2025-Mar "" "get function name"
.SH NAME
get_functionName \- get_functionName(f)
.SH SYNOPSIS
\fIget_functionName(f)\fR
.SH OPTIONS
.PP
\fBf\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.get_functionName at app_name.R:line 81
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
