.TH HAS_CACHEFILE 1 2023-Jun "" "has_cachefile"
.SH NAME
has_cachefile \- has_cachefile(filepath)
.SH SYNOPSIS
\fIhas_cachefile(filepath)\fR
.SH OPTIONS
.PP
\fBfilepath\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.has_cachefile at cache.R:line 19
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
