.TH HAS_CACHEFILE 1 2026-7月 "" "Check Whether a Cache File Exists"
.SH NAME
has_cachefile \- has_cachefile(filepath)
.SH SYNOPSIS
\fIhas_cachefile(filepath)\fR
.SH DESCRIPTION
.PP


Tests whether a given cache file path refers to an existing,
non-empty file that can be safely reused as a cache. The function
returns \code{FALSE} for any of the following situations:
\enumerate{
\item the \code{filepath} value is \code{NULL};
\item the \code{filepath} value is an empty string;
\item the file does not exist on disk;
\item the file exists but has a size of zero bytes.
}
.PP
.SH OPTIONS
.PP
\fBfilepath\fB \fR\- . a character vector of the cache file path to be
tested.
.PP
.SH VALUE
.PP
A logical value that indicates whether the specific given file is
a valid cache file. The value \code{TRUE} is returned only when the
file exists and has a non-zero size; \code{FALSE} is returned
otherwise.
.PP
.SH SEE ALSO
\code{\link{use_cache}}, \code{\link{file.exists}},
\code{\link{file.size}}
.SH FILES
.PP
SMRUCC/R#.declare_function.has_cachefile at cache.R:line 76
.PP
.SH AUTHOR
Written by \fBxieguigang\fR
.SH COPYRIGHT
Copyright © xieguigang, MIT + file LICENSE Licensed 2026
