.TH HAS_CACHEFILE 1 2025-Jun "" "check the cache file is exists or not"
.SH NAME
has_cachefile \- has_cachefile(filepath)
.SH SYNOPSIS
\fIhas_cachefile(filepath)\fR
.SH OPTIONS
.PP
\fBfilepath\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.has_cachefile at cache.R:line 30
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
