.TH HOOK 1 2023-Jul "" "Add workflow app component into the registry"
.SH NAME
hook \- hook(app)
.SH SYNOPSIS
\fIhook(app)\fR
.SH OPTIONS
.PP
\fBapp\fB \fR\- . the app object which is generated via the ``app`` function
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.hook at hook.R:line 5
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
