.TH INIT_CONTEXT 1 2025-Jun "" "This function should be call at first"
.SH NAME
init_context \- init_context(
    <i>outputdir</i> = <span style='color: brown;'><strong>'./'</strong></span>)
.SH SYNOPSIS
\fIinit_context(
    <i>outputdir</i> = <span style='color: brown;'><strong>'./'</strong></span>)\fR
.SH OPTIONS
.PP
\fBoutputdir\fB \fR\- './'. the directory path to the workflow analysis workspace, default path value is current directory.
.PP
.SH VALUE
.PP
this function has no return value. and the constructed analysis environment context object will be saved in the global environment with symbol name ``&[workflow_render]``.
.PP
.SH DETAILS
.PP
for construct of the runtime environment, the generated context environment for run the analysis workflow has member slots of: 1. root: a character vector for the ``outputdir`` directory path. 2. analysis: a character vector for the directory path that contains the analysis result output from current workflow process. 3. temp_dir: a character vector for the directory path that contains the analysis temp files from current workflow process. 4. t0: a date time stamp when start current analysis workflow. 5. workflow: a tuple list object that contains the analysis application object that constructed from the ``app`` function. 6. pipeline: a character vector for run the application workflow.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.init_context at context.R:line 27
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
