.TH INIT_CONTEXT 1 2023-Apr "" "This function should be call at first"
.SH NAME
init_context \- init_context(
    <i>outputdir</i> = ./)
.SH SYNOPSIS
\fIinit_context(
    <i>outputdir</i> = ./)\fR
.SH OPTIONS
.PP
\fBoutputdir\fB \fR\- ./. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.init_context at context.R:line 3
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
