.TH MAP_COLORS 1 2023-Mar "" "map_colors"
.SH NAME
map_colors \- map_colors(values,
    <i>colors</i> = [blue, gray, red],
    <i>levels</i> = 25)
.SH SYNOPSIS
\fImap_colors(values,
    <i>colors</i> = [blue, gray, red],
    <i>levels</i> = 25)\fR
.SH OPTIONS
.PP
\fBvalues\fB \fR\- . 
.PP
.PP
\fBcolors\fB \fR\- [blue, gray, red]. 
.PP
.PP
\fBlevels\fB \fR\- 25. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.map_colors at styles.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
