.TH MAP_COLORS 1 2021-05-26 "" "map_colors"
.SH NAME
map_colors \- map_colors(values, colors = [blue, gray, red], levels = 25)
.SH SYNOPSIS
\fImap_colors(values, colors = [blue, gray, red], levels = 25)\fR
.SH OPTIONS
.PP
\fBvalues\fB \fR\- 
.PP
.PP
\fBcolors\fB \fR\- [blue, gray, red]
.PP
.PP
\fBlevels\fB \fR\- 25
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.map_colors at styles.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2021
