.TH MAP_SIZE 1 2021-05-27 "" "map_size"
.SH NAME
map_size \- map_size(values, min = 1, max = 10)
.SH SYNOPSIS
\fImap_size(values, min = 1, max = 10)\fR
.SH OPTIONS
.PP
\fBvalues\fB \fR\- 
.PP
.PP
\fBmin\fB \fR\- 1
.PP
.PP
\fBmax\fB \fR\- 10
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.map_size at styles.R:line 31
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2021
