.TH MAP_CLASSCOLORS 1 2021-05-27 "" "map_classColors"
.SH NAME
map_classColors \- map_classColors(values, colors, missing = gray)
.SH SYNOPSIS
\fImap_classColors(values, colors, missing = gray)\fR
.SH OPTIONS
.PP
\fBvalues\fB \fR\- 
.PP
.PP
\fBcolors\fB \fR\- 
.PP
.PP
\fBmissing\fB \fR\- gray
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.map_classColors at styles.R:line 9
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2021
