.TH MAPEDGE 1 2021-05-26 "" "mapEdge"
.SH NAME
mapEdge \- mapEdge(edges, from = from, to = to, weight = weight, type = type, color = color, width = width, dash = dash)
.SH SYNOPSIS
\fImapEdge(edges, from = from, to = to, weight = weight, type = type, color = color, width = width, dash = dash)\fR
.SH OPTIONS
.PP
\fBedges\fB \fR\- 
.PP
.PP
\fBfrom\fB \fR\- from
.PP
.PP
\fBto\fB \fR\- to
.PP
.PP
\fBweight\fB \fR\- weight
.PP
.PP
\fBtype\fB \fR\- type
.PP
.PP
\fBcolor\fB \fR\- color
.PP
.PP
\fBwidth\fB \fR\- width
.PP
.PP
\fBdash\fB \fR\- dash
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.mapEdge at table.R:line 6
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2021
