.TH MAPEDGE 1 2023-Mar "" "mapEdge"
.SH NAME
mapEdge \- mapEdge(edges,
    <i>from</i> = from,
    <i>to</i> = to,
    <i>weight</i> = weight,
    <i>type</i> = type,
    <i>color</i> = color,
    <i>width</i> = width,
    <i>dash</i> = dash)
.SH SYNOPSIS
\fImapEdge(edges,
    <i>from</i> = from,
    <i>to</i> = to,
    <i>weight</i> = weight,
    <i>type</i> = type,
    <i>color</i> = color,
    <i>width</i> = width,
    <i>dash</i> = dash)\fR
.SH OPTIONS
.PP
\fBedges\fB \fR\- . 
.PP
.PP
\fBfrom\fB \fR\- from. 
.PP
.PP
\fBto\fB \fR\- to. 
.PP
.PP
\fBweight\fB \fR\- weight. 
.PP
.PP
\fBtype\fB \fR\- type. 
.PP
.PP
\fBcolor\fB \fR\- color. 
.PP
.PP
\fBwidth\fB \fR\- width. 
.PP
.PP
\fBdash\fB \fR\- dash. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.mapEdge at table.R:line 6
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
