.TH MAPNODE 1 2021-05-27 "" "mapNode"
.SH NAME
mapNode \- mapNode(nodes, group = group, label = label, color = color, shape = shape, size = size)
.SH SYNOPSIS
\fImapNode(nodes, group = group, label = label, color = color, shape = shape, size = size)\fR
.SH OPTIONS
.PP
\fBnodes\fB \fR\- 
.PP
.PP
\fBgroup\fB \fR\- group
.PP
.PP
\fBlabel\fB \fR\- label
.PP
.PP
\fBcolor\fB \fR\- color
.PP
.PP
\fBshape\fB \fR\- shape
.PP
.PP
\fBsize\fB \fR\- size
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.mapNode at table.R:line 27
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2021
