.TH MAPNODE 1 2023-Mar "" "mapNode"
.SH NAME
mapNode \- mapNode(nodes,
    <i>group</i> = group,
    <i>label</i> = label,
    <i>color</i> = color,
    <i>shape</i> = shape,
    <i>size</i> = size)
.SH SYNOPSIS
\fImapNode(nodes,
    <i>group</i> = group,
    <i>label</i> = label,
    <i>color</i> = color,
    <i>shape</i> = shape,
    <i>size</i> = size)\fR
.SH OPTIONS
.PP
\fBnodes\fB \fR\- . 
.PP
.PP
\fBgroup\fB \fR\- group. 
.PP
.PP
\fBlabel\fB \fR\- label. 
.PP
.PP
\fBcolor\fB \fR\- color. 
.PP
.PP
\fBshape\fB \fR\- shape. 
.PP
.PP
\fBsize\fB \fR\- size. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.mapNode at table.R:line 27
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
