.TH MAPSTYLECOLORS 1 2021-05-27 "" "mapStyleColors"
.SH NAME
mapStyleColors \- mapStyleColors(table, values = weight, colors = [blue, gray, red], levels = 25)
.SH SYNOPSIS
\fImapStyleColors(table, values = weight, colors = [blue, gray, red], levels = 25)\fR
.SH OPTIONS
.PP
\fBtable\fB \fR\- 
.PP
.PP
\fBvalues\fB \fR\- weight
.PP
.PP
\fBcolors\fB \fR\- [blue, gray, red]
.PP
.PP
\fBlevels\fB \fR\- 25
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.mapStyleColors at styles.R:line 41
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2021
