.TH MAPSTYLEWIDTH 1 2021-05-27 "" "mapStyleWidth"
.SH NAME
mapStyleWidth \- mapStyleWidth(table, values = weight, min = 1, max = 10)
.SH SYNOPSIS
\fImapStyleWidth(table, values = weight, min = 1, max = 10)\fR
.SH OPTIONS
.PP
\fBtable\fB \fR\- 
.PP
.PP
\fBvalues\fB \fR\- weight
.PP
.PP
\fBmin\fB \fR\- 1
.PP
.PP
\fBmax\fB \fR\- 10
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.mapStyleWidth at styles.R:line 48
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2021
