.TH MAPSTYLEWIDTH 1 2023-Mar "" "mapStyleWidth"
.SH NAME
mapStyleWidth \- mapStyleWidth(table,
    <i>values</i> = weight,
    <i>min</i> = 1,
    <i>max</i> = 10)
.SH SYNOPSIS
\fImapStyleWidth(table,
    <i>values</i> = weight,
    <i>min</i> = 1,
    <i>max</i> = 10)\fR
.SH OPTIONS
.PP
\fBtable\fB \fR\- . 
.PP
.PP
\fBvalues\fB \fR\- weight. 
.PP
.PP
\fBmin\fB \fR\- 1. 
.PP
.PP
\fBmax\fB \fR\- 10. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.mapStyleWidth at styles.R:line 48
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
