.TH MAPSTYLESIZE 1 2021-05-27 "" "mapStyleSize"
.SH NAME
mapStyleSize \- mapStyleSize(table, values = weight, min = 10, max = 80)
.SH SYNOPSIS
\fImapStyleSize(table, values = weight, min = 10, max = 80)\fR
.SH OPTIONS
.PP
\fBtable\fB \fR\- 
.PP
.PP
\fBvalues\fB \fR\- weight
.PP
.PP
\fBmin\fB \fR\- 10
.PP
.PP
\fBmax\fB \fR\- 80
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.mapStyleSize at styles.R:line 55
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2021
