.TH RUN 1 2025-Aug "" "Call this function to start run workflow"
.SH NAME
run \- run(
    <i>registry</i> = <span style='color: blue !important;'>NULL</span>,
    <i>disables</i> = 'list'())
.SH SYNOPSIS
\fIrun(
    <i>registry</i> = <span style='color: blue !important;'>NULL</span>,
    <i>disables</i> = 'list'())\fR
.SH OPTIONS
.PP
\fBregistry\fB \fR\- NULL. a callable function for create the workflow registry,
this parameter could be nothing if this workflow processor apps has
been registered into the workflow as the processor components via
the ``hook`` function.
.PP
.PP
\fBdisables\fB \fR\- 'list'(). a tuple list object that contains the workflow module
activate swtches. the list tuple key name should be the analysis app
name and the corresponding slot value should be a logical value for
indicates that the workflow module is disable or not: true for disable
and skip, and false or null and missing for enable the corresponding
workflow module
.PP
.SH DETAILS
.PP
A workflow is consist with a set of the analysis modules in side,
the executative sequence define in workflow is based on the module name
vector in the pipeline data slot
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.run at workflowRender.R:line 18
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
