.TH RUN 1 2023-May "" "run"
.SH NAME
run \- run(
    <i>registry</i> = <span style='color: blue;'>NULL</span>)
.SH SYNOPSIS
\fIrun(
    <i>registry</i> = <span style='color: blue;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBregistry\fB \fR\- NULL. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.run at workflowRender.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
