.TH SET_CONFIG 1 2025-Jan "" "Set user parameters to the workflow context"
.SH NAME
set_config \- set_config(
    <i>configs</i> = 'list'())
.SH SYNOPSIS
\fIset_config(
    <i>configs</i> = 'list'())\fR
.SH OPTIONS
.PP
\fBconfigs\fB \fR\- 'list'(). a key-value paire tuple list object that contains the workflow parameter values.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.set_config at set_config.R:line 6
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
