.TH SET_DISABLE 1 2025-Jun "" "Set workflow application disable flag"
.SH NAME
set_disable \- set_disable(app,
    <i>flag</i> = <span style='color: blue !important;'>TRUE</span>)
.SH SYNOPSIS
\fIset_disable(app,
    <i>flag</i> = <span style='color: blue !important;'>TRUE</span>)\fR
.SH OPTIONS
.PP
\fBapp\fB \fR\- . 
.PP
.PP
\fBflag\fB \fR\- TRUE. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.set_disable at set_disable.R:line 5
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
