.TH SETVERTEX 1 2023-Mar "" "Config of the nodes attributes in the graph"
.SH NAME
setVertex \- setVertex(g, nodes,
    <i>hasLayout</i> = <span style='color: blue;'>TRUE</span>,
    <i>algorithm</i> = edge_weighted,
    <i>weightedFactor</i> = 10)
.SH SYNOPSIS
\fIsetVertex(g, nodes,
    <i>hasLayout</i> = <span style='color: blue;'>TRUE</span>,
    <i>algorithm</i> = edge_weighted,
    <i>weightedFactor</i> = 10)\fR
.SH OPTIONS
.PP
\fBg\fB \fR\- . the network graph
.PP
.PP
\fBnodes\fB \fR\- . the nodes property table, the row names of this table must be the node id in the graph object.
.PP
.PP
\fBhasLayout\fB \fR\- TRUE. if this parameter is TRUE, then it means the nodes layout data is already been in the ``nodes`` table, then we will apply the layout data from the nodes table rather than generates new layout from run algorithm.
.PP
.PP
\fBalgorithm\fB \fR\- edge_weighted. 
.PP
.PP
\fBweightedFactor\fB \fR\- 10. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.setVertex at graph.R:line 52
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
