.TH SETVERTEX 1 2021-05-27 "" "Config of the nodes attributes in the graph"
.SH NAME
setVertex \- setVertex(g, nodes, hasLayout = TRUE, algorithm = edge_weighted, weightedFactor = 10)
.SH SYNOPSIS
\fIsetVertex(g, nodes, hasLayout = TRUE, algorithm = edge_weighted, weightedFactor = 10)\fR
.SH OPTIONS
.PP
\fBg\fB \fR\- 
.PP
.PP
\fBnodes\fB \fR\- 
.PP
.PP
\fBhasLayout\fB \fR\- TRUE
.PP
.PP
\fBalgorithm\fB \fR\- edge_weighted
.PP
.PP
\fBweightedFactor\fB \fR\- 10
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.setVertex at graph.R:line 52
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2021
