.TH STYLEINDEX 1 2021-05-26 "" "Create index list of the given styles data"
.SH NAME
styleIndex \- styleIndex(from, to, style = NULL)
.SH SYNOPSIS
\fIstyleIndex(from, to, style = NULL)\fR
.SH OPTIONS
.PP
\fBfrom\fB \fR\- 
.PP
.PP
\fBto\fB \fR\- 
.PP
.PP
\fBstyle\fB \fR\- NULL
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.styleIndex at graph.R:line 81
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2021
