.TH TABULATE_WORKFLOW_SUMMARY 1 2024-Nov "" "Extract the workflow analysis contents"
.SH NAME
tabulate_workflow_summary \- tabulate_workflow_summary(pool)
.SH SYNOPSIS
\fItabulate_workflow_summary(pool)\fR
.SH OPTIONS
.PP
\fBpool\fB \fR\- . 
.PP
.SH VALUE
.PP
a dataframe object that contains the workflow analysis modules information, example as the reference name, description, dependency information, etc.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.tabulate_workflow_summary at summary.R:line 28
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2024
