.TH THROW_ERR 1 2023-Aug "" "echo error message on the screen and then crash the workflow"
.SH NAME
throw_err \- throw_err(msg)
.SH SYNOPSIS
\fIthrow_err(msg)\fR
.SH OPTIONS
.PP
\fBmsg\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.throw_err at utils.R:line 26
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
