.TH USE_CACHE 1 2024-Jan "" "Work with cache file"
.SH NAME
use_cache \- use_cache(filepath, create)
.SH SYNOPSIS
\fIuse_cache(filepath, create)\fR
.SH OPTIONS
.PP
\fBfilepath\fB \fR\- . 
.PP
.PP
\fBcreate\fB \fR\- . a callable function that accept a file path parameter to create the target cache file.
.PP
.SH DETAILS
.PP
this function will work around with the specific given cache file: this function will do nothing if the cache file is already exists or invoke the ``create`` function for when file exists of the cache data is false.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.use_cache at cache.R:line 11
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2024
