.TH USE_CACHE 1 2025-Aug "" "Work with cache file"
.SH NAME
use_cache \- use_cache(filepath, create)
.SH SYNOPSIS
\fIuse_cache(filepath, create)\fR
.SH OPTIONS
.PP
\fBfilepath\fB \fR\- . 
.PP
.PP
\fBcreate\fB \fR\- . a callable function that accept a file path parameter to create the target cache file.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.use_cache at cache.R:line 11
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
