.TH WORKSPACE_TEMPROOT 1 2026-7月 "" "Get the Workspace Temporary Root Directory"
.SH NAME
workspace_temproot \- workspace_temproot(
    <i>ssid</i> = <span style='color: blue !important;'>NULL</span>)
.SH SYNOPSIS
\fIworkspace_temproot(
    <i>ssid</i> = <span style='color: blue !important;'>NULL</span>)\fR
.SH DESCRIPTION
.PP


Returns the temporary root directory of the current workflow
workspace. This directory holds all of the intermediate files
produced by the workflow modules, including the per-application
workspace directories returned by \code{\link{workspace}}.
.PP
.SH OPTIONS
.PP
\fBssid\fB \fR\- NULL. the session identifier used for the multi-user
environment. The default value of \code{NULL} refers to the
global user environment.
.PP
.SH VALUE
.PP
A character vector of the temporary root directory path of the
workflow workspace.
.PP
.SH DETAILS
.PP
The returned path corresponds to the \code{temp_dir} slot of the
workflow context, which is initialized by
\code{\link{init_context}} to \code{<outputdir>/tmp/}.
.PP
.SH EXAMPLES
.PP
#\dontrun{

tmp <- workspace_temproot();

#}
.PP
.SH SEE ALSO
\code{\link{init_context}}, \code{\link{workdir_root}},
\code{\link{result_dir}}, \code{\link{workspace}},
\code{\link{.get_context}}
.SH FILES
.PP
SMRUCC/R#.declare_function.workspace_temproot at workdir.R:line 102
.PP
.SH AUTHOR
Written by \fBxieguigang\fR
.SH COPYRIGHT
Copyright © xieguigang, MIT + file LICENSE Licensed 2026
