.TH WORKSPACE_TEMPROOT 1 2025-Jun "" "workspace_temproot"
.SH NAME
workspace_temproot \- workspace_temproot(
    <i>ssid</i> = <span style='color: blue !important;'>NULL</span>)
.SH SYNOPSIS
\fIworkspace_temproot(
    <i>ssid</i> = <span style='color: blue !important;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBssid\fB \fR\- NULL. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.workspace_temproot at workspace.R:line 91
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
