.TH WORKDIR_ROOT 1 2025-Jun "" "Get workspace root directory"
.SH NAME
workdir_root \- workdir_root(
    <i>ssid</i> = <span style='color: blue !important;'>NULL</span>)
.SH SYNOPSIS
\fIworkdir_root(
    <i>ssid</i> = <span style='color: blue !important;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBssid\fB \fR\- NULL. 
.PP
.SH DETAILS
.PP
actually this function will returns the ``output`` dir path which is set via the ``init_context`` function
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.workdir_root at workspace.R:line 78
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
