.TH WORKFILE 1 2023-10月 "" "Construct of the file path inside an app workspace"
.SH NAME
workfile \- workfile(app, relpath)
.SH SYNOPSIS
\fIworkfile(app, relpath)\fR
.SH OPTIONS
.PP
\fBapp\fB \fR\- . 
.PP
.PP
\fBrelpath\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.workfile at workspace.R:line 33
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
