.TH WORKSPACE 1 2023-Jul "" "get app workspace location"
.SH NAME
workspace \- workspace(app)
.SH SYNOPSIS
\fIworkspace(app)\fR
.SH OPTIONS
.PP
\fBapp\fB \fR\- . the app list object or just the app name its character text value.
.PP
.SH VALUE
.PP
a character vector of the workspace directory path of the specific analysis application.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.workspace at workspace.R:line 10
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
