.TH WORKSPACE 1 2025-Jul "" "get app workspace location"
.SH NAME
workspace \- workspace(app,
    <i>ssid</i> = <span style='color: blue !important;'>NULL</span>)
.SH SYNOPSIS
\fIworkspace(app,
    <i>ssid</i> = <span style='color: blue !important;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBapp\fB \fR\- . 
.PP
.PP
\fBssid\fB \fR\- NULL. the session id for multiple user environment, default NULL means global user environment
.PP
.SH VALUE
.PP
a character vector of the workspace directory path of the specific analysis application.
.PP
.SH DETAILS
.PP
the verbose option could be config from the commandline option: ``--verbose``
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.workspace at workspace.R:line 14
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
