.TH WORKFILE 1 2024-Feb "" "Construct of the file path inside an app workspace"
.SH NAME
workfile \- workfile(app,
    <i>relpath</i> = <span style='color: blue !important;'>NULL</span>)
.SH SYNOPSIS
\fIworkfile(app,
    <i>relpath</i> = <span style='color: blue !important;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBapp\fB \fR\- . this app parameter value could be in 3 kinds of data type: 1. app tuple list object, which is created via the ``app`` function. 2. the app name character vector 3. the workfile path expression, should be in format like: ``app://relpath/to/file.ext``
.PP
.PP
\fBrelpath\fB \fR\- NULL. 
.PP
.SH DETAILS
.PP
the workfile path expression is in format string of: ``app://filepath``, example as ``getMzSet://mzset.txt``, where we could parse the reference information from this character string: app name is ``getMzSet``, and the relpath data is ``mzset.txt``. so, such configuation could be equals to the function invoke of the workfile function: ``workfile("getMzSet", "/mzset.txt");``.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.workfile at workspace.R:line 52
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2024
